### ISSUE TITLE
打包 npm run builder 报错了

### ISSUE THREAD

**Issue by vzane** [laterly/electron-vue3-vite#3]
Application entry file "dist\main.js" in the "E:\test\dist\win-ia32-unpacked\resources\app.asar" does not exis
ems like a wrong configuration.  stackTrace=

**Comment by fy-xiaofeng** [comment]
I reported the same error

**Comment by laterly** [comment]
> I reported the same error

@fy-xiaofeng 
Some dependencies may not have installed successfully. Please fetch the latest code, then delete the node_modules folder, reinstall the dependencies with ‘pnpm install’, and then run ‘pnpm run builder’.

**Comment by fy-xiaofeng** [comment]
> > I reported the same error
> 
> @fy-xiaofeng Some dependencies may not have installed successfully. Please fetch the latest code, then delete the node_modules folder, reinstall the dependencies with ‘pnpm install’, and then run ‘pnpm run builder’.

Thank you for your answer. I solved my problem because vue mixed with electron. I created a separate electron folder and solved it
